### ISSUE TITLE
[1.12.1] Crash on world load?

### ISSUE THREAD

**Issue by MokahTGS** [malte0811/IndustrialWires#13]
I'm getting a crash on world load that started with updating this but doesn't seem to be affected when I role back to an earlier version.

The crash is IC2 but I didn't update that.  Not sure what changed as this world save was working yesterday.

https://pastebin.com/ne0c6Py7

**Comment by malte0811** [comment]
I have no idea what could be causing this, esp. if it is something in IndustrialWires. A crash with the energy net I would understand, but this is the wind calculations. Those calculations involve just the maximum world height and the average ground height. I don't see how I am affecting either of those in IW.
You updated just IW? And reverting just IW fixes it?

**Comment by MokahTGS** [comment]
Reverting does not fix it.  Removing IC2 and IW fixes it...which is not optimal.

**Comment by malte0811** [comment]
Does removing just IW fix it?

**Comment by MokahTGS** [comment]
Nope

**Comment by malte0811** [comment]
I'm pretty certain this is an IC2 issue. As I said I don't see how I could be affecting this.
@MokahTGS did you update just IW when this started or some other mod at the same time?
@Aroma1997 Any ideas/Is this on your side? I can think of one single weird thing I do in the new build that is even remotely related: I have TE's that implement IC2 energy interfaces (but don't register to the net) that replace themselves with other TE's (that implement IC2 energy interfaces as well, but register to the net) in their first tick (see [here](https://github.com/malte0811/IndustrialWires/blob/MC1.12/src/main/java/malte0811/industrialWires/blocks/wire/DummyTEs.java)). I do that because I managed to forget the colon (:) in the TE name when registering it, so it was `minecraft:industrialwiresic2...`. And those fake TE's seem to be the easiest way of moving TE's from one name to another in 1.12.

**Comment by MokahTGS** [comment]
So this turned out to be a Pulvis issue with how the dynamically generate dusts.

**Comment by Aroma1997** [comment]
Something makes the wind calculation matrix non-invertable, so there's no unique solution.
Do you still have a log file of that happening (full log, not crash log).
I'd really like to know how that's happening and how pulvus generates dusts.

**Comment by malte0811** [comment]
The "Pulvis" issue is probably unrelated if it is oitsjustjose/Pulver#5 (except it caused crashes when @MokahTGS tried to remove IC2). I couldn't find any mods named "Pulvis", "Pulver" was the closest and the issue I linked makes some sense in the context.

**Comment by MokahTGS** [comment]
Pulver yes not pulvis

**Comment by MokahTGS** [comment]
I'm no longer having the issue as pulver has patched the issue.
