### ISSUE TITLE
IW1.6-20 hard dependand on MK1.12.1

### ISSUE THREAD

**Issue by Kilmatar** [malte0811/IndustrialWires#14]
Version 1.6-20 marked as compatible with MK1.12 & MK1.12.1 but in reality is hard dependand on MK1.12.1
![image](https://user-images.githubusercontent.com/4357221/30593260-a7280b74-9d52-11e7-8cbc-f6f52783e110.png)

![image](https://user-images.githubusercontent.com/4357221/30593293-bbf77f9e-9d52-11e7-8eba-eb9d04c3df5e.png)

**Comment by malte0811** [comment]
That's because I used a 1.12.1 Forge version when I built the mod. I didn't think about it affecting the version the mod is for according to `mcmod.info`. I marked the file as compatible with 1.12.1 and 1.12.2 now since IE 0.12-72 (which IW 1.6-20 depends on) has the same issue (so uploading a new build would just cause the error to say Immersive Engineering rather than Industrial Wires).
