### ISSUE TITLE
Does not seem to work with ic2 classic.

### ISSUE THREAD

**Issue by Trinsdar** [malte0811/IndustrialWires#40]
When I installed this mod with ic2 classic, the wires would not transfer eu and the teirs are one too high for ic2 classic, ase tin should be 5 eu/tick, copper should be 32 eu/tick, gold should be 128 eu/tick, and glass fiber should be 512 eu/tick. the hv one is fine. 
 
Minecraft 1.12.2
Ic2 classic 2.2.999
Industrial wires 1.7-29

**Comment by malte0811** [comment]
From the [contributing guidelines](https://github.com/malte0811/IndustrialWires/blob/MC1.12/CONTRIBUTING.md), the last item in the list of unsupported mods:
 > - **Any version of IndustrialCraft2 that is not made by the official IC2 team** (more specifically, any IC2 version not available for download [here](http://jenkins.ic2.player.to/) or [here](https://minecraft.curseforge.com/projects/industrial-craft))

This includes IC2 classic.
I will add a config option for the transfer rates (like the one IE has), but unless you find a scenario where the wires don't transfer energy with IC2 Experimental that part of the issue is invalid/irrelevant to me.

**Comment by Trinsdar** [comment]
yep looks like only ic2 classic is having the problem.
Edit: after a while it started transferring for whatever reason; I have no idea wtf is going on.
Edit 2: in another instance with just ic2 classic, immersive engineering, and industrial wires it won't transfer. I've asked speiger to see if there is anything he can do on his end since you don't want to do anything about it on your end.
