### ISSUE TITLE
[Suggestion] Easy conversion of EU to RF

### ISSUE THREAD

**Issue by vishtheshnu** [malte0811/IndustrialWires#42]
Using the latest version of the mod, I'm able to convert RF into EU with connectors and wire. The engineer's manual says that a multiblock structure is needed to convert them the other way around. Generally, there are many ways to produce RF/FE across many mods, while EU production is more limited. Thus it feels like players who wish to focus on IC2's generators are punished due to the higher difficulty in converting EU into RF.

So, I propose that you allow easy conversion between EU and RF **both ways** using just connectors and wire. Or at least add a config option to allow such an option, since I'm making an infinity evolved: expert inspired modpack right now, and EU to RF conversion would be nice as well.

**Comment by malte0811** [comment]
The conversion is definitely not intended, I'm preparing to release a build with a fix right now. I will not add a config option for "simple" conversion, because simple conversion a) isn't the goal of IW, b) isn't my style and c) would remove half of the purpose of the mechanical multiblocks that I spent quite a lot of time creating.

**Comment by vishtheshnu** [comment]
Sounds good then. I'm glad I was able to inform you of the unintended
behavior.
