### ISSUE TITLE
Other converter very buggy :(

### ISSUE THREAD

**Issue by anar4732** [malte0811/IndustrialWires#55]
Project Red Input: Not Working
![image](https://user-images.githubusercontent.com/10792085/50465053-169f2a00-09ae-11e9-9b5b-e141e1aa7fc7.png)
![image](https://user-images.githubusercontent.com/10792085/50465050-0f781c00-09ae-11e9-8a31-cad73498ce07.png)

Project Red Output: Working
![image](https://user-images.githubusercontent.com/10792085/50465044-0424f080-09ae-11e9-8a07-b14ae48fe478.png)

Project Red Input With Repeater: Working (WTF?)
![image](https://user-images.githubusercontent.com/10792085/50465034-f5d6d480-09ad-11e9-8be6-0bb50542dec8.png)
but signal showing 14 Instead 15?

**Comment by LemADEC** [comment]
Pictures aren't reachable, please use another site or directly paste in the issue ticket

**Comment by anar4732** [comment]
> Pictures aren't reachable, please use another site or directly paste in the issue ticket
I updated.

**Comment by anar4732** [comment]
I updated

**Comment by LemADEC** [comment]
Check the signal strength, maybe?

**Comment by malte0811** [comment]
I haven't been able to reproduce this issue at all. The "other" RS controller doesn't keep its IO state across world/chunk reloads, that will be fixed in the next release. Panels showing 14 rather than 15 for P:R wires should be fixed then as well.
Could you post a mod list and detailed steps for reproducing the issue? There's a decent chance I'm unable to replicate this due to some little detail (something like the order in which I placed things) being different from your setup.

**Comment by anar4732** [comment]
Ok.
I found the bug in PR.
![2019-01-10_02 35 54](https://user-images.githubusercontent.com/10792085/50934106-18beb980-1481-11e9-93e8-b0c48166358d.png)

And, Yes. it is #59
![2019-01-10_02 38 59](https://user-images.githubusercontent.com/10792085/50934154-41df4a00-1481-11e9-81ed-2927ef7ffa01.png)
Please release next version to understand that.
