### ISSUE TITLE
Crash when breake redstone connector its connected control panels

### ISSUE THREAD

**Issue by anar4732** [malte0811/IndustrialWires#56]
https://pastebin.com/raw/Jd4xhAhC

Version: 1.7.33

**Comment by malte0811** [comment]
A full crash report would be helpful, esp. since the crash in completely in IE code. I won't be able to release a fix for the next ~1.5 weeks though.

**Comment by malte0811** [comment]
I tried to replicate this in my test world in a couple of different setups, but wasn't able to reproduce the crash. What version of IE are you using, does it still happen with the latest IE build (0.12-88) and could you upload a full crashlog rather than just the stacktrace?

**Comment by anar4732** [comment]
I did not update any mods but the crash is gone, interesting...

**Comment by anar4732** [comment]
https://paste.dimdev.org/jarutidafe.mccrash

**Comment by anar4732** [comment]
1. Connect a control panel to IE's redstone wire connector
2. Make a debug crash
3. See the mesage "cannot connect this wire here" (#51)
4. Break the IE's redstone wire connector

**Comment by malte0811** [comment]
I went through the steps you mentioned exactly as you said, but wasn't able to replicate the (second) crash. From the crash it looks like this is caused by the wire not being there "on both ends" (only the control panel knows it has a connection to the connector, the connector doesn't). I haven't seen that happen for ~3 years, and I thought there wasn't any way for it to happen any more.
Is the wire still visible after the first crash? Point 3 seems to suggest it isn't visible, but it was still visible in all of my tests. Could you try placing the panel+connector such that the wire crosses a chunk boundary? That should show which ends of the wire still "know they're there".
Could you try (in a test world) whether this happens without Immersive Tech, and maybe even without VanillaFix? VF because I don't trust the concept in general, though I don't *think* it would cause this. IT because they do some shoddy things related to wires, which can cause issues like the "cannot connect wire" one (It's supposed to be fixed since September, but the code is still there in the latest file on CF).

**Comment by anar4732** [comment]
May be fixing #51 fixes this

**Comment by anar4732** [comment]
![2019-01-25_16 28 26](https://user-images.githubusercontent.com/10792085/51746072-601e8a00-20be-11e9-9066-6abb3437f7ab.png)
Understanding this bug is very difficult.
NOTE: I I have encountered this bug in a dedicated server, and nothing in my test world
> Is the wire still visible after the first crash?

is visible but not connectable due "cannot connect this wire here" and brak this in the dedicated server boom client side crash, not server.  repeat this in test world = nothing
