### ISSUE TITLE
Math Bug - Rotation to Kinetic

### ISSUE THREAD

**Issue by Utildayael** [malte0811/IndustrialWires#6]
I think this is a simple math bug but I could be wrong. 

Using IE waterwheels (3) attached to an industrial wires rotational to kinetic which is then attached to an IC2 kinetic generator I am producing 229 EU/t. Normally the IE wheels can only get (at optimum setup) a little under 90 RF/t. Depending on the mod, EU:RF is usually 1:3 or 1:4 so I would expect to have 1/3 or 1/4 of 90RF as EU but instead I'm getting 3x. :)

Hope that makes sense. I can get more specific measurements if needed (going off memory) but seems to be about 3x multiplier instead of divider. 

Thanks

**Comment by malte0811** [comment]
Yeah, I messed up when setting default values for the config. You can fix this by setting `euPerIf` to 0.25 instead of 4 in the config. I will fix this in the next release, which probably won't happen too soon as I am working on a pretty complex feature (and this bug can easily be worked around by server owners/pack devs).

**Comment by Utildayael** [comment]
Oops. I should have checked the config! Glad you put that in there. :)

Thank you sir!
