### ISSUE TITLE
Losing EU from Batbox when idle

### ISSUE THREAD

**Issue by Motridox** [malte0811/IndustrialWires#7]
Hi, there's a bug where you seem to lose EU for no reason out of a batbox.

This is my test setup with your mod.

BatBox -> Tin Connector -> Electric Furnace

Put in a iron block, after it's finished the bat box seem to be fine, no energy loss.

But as soon as I use a Tin Relay i lose power into nothing.

Setup:

BatBox -> Tin Connector -> Tin Relay -> Electric Furnace

After then cooking is finished the batbox is losing energy each second. It's a small amount (around ~100 eu)

Am I doing something wrong or is that intended?

EDIT: Somehow also losing energy when i break the Tin Relay and connect the furnace directly to the batbox.

**Comment by malte0811** [comment]
I haven't been able to reproduce this bug in my development environment. What versions of IC2 (including classic vs experimental), IE and IW and what other mods do you have installed (link to the modpack would work as well, if it is a public one)? Any config changes (especially energy related ones)?
If this happens when connecting the furnace directly to the batbox as well (so with no IndustrialWires blocks involved) you might want to report this to the IC2 team?

**Comment by malte0811** [comment]
Sorry, I understood your edit to mean that you were losing energy even when placing the batbox and furnace next to each other, leading me to think that this was an IC2 bug. It is actually an IW bug, I'll push a fix soon. I want to include some changes/additions I made in 1.11 in the next build, so I might not get it done today (should be ready tomorrow though).

**Comment by Motridox** [comment]
Hey,

we downgraded to minecraft 1.7.10, but I will take a look at the 1.10.2
version when I get my external hdd back.

I remember that I used the recommended version for everything 3 weeks ago.

Greetings
mTrX

2017-05-07 20:11 GMT+02:00 malte0811 <notifications@github.com>:
