### ISSUE TITLE
[Question] Is this project supported?

### ISSUE THREAD

**Issue by Orygeunik** [malte0811/IndustrialWires#84]
* I see that the last commit to the repository was a long time ago.

* I also see that there are some PR that hang without merging, although it does not seem to introduce a regression. For example: #77; #76; #75;
* Also, issues hang without Your comments or messages.

* But at the same time, if You look at your activity (on the screen), You can see that you are using GitHub.
![Аннотация 2019-12-25 015731](https://user-images.githubusercontent.com/6960655/71426402-f89c0080-26b9-11ea-92fa-6942024157e9.png)

Given this, I would like to know this project is "alive" (supported) or have You lost interest in it?

**Comment by malte0811** [comment]
It currently isn't supported, for 2 main reasons:
1. I have too many projects (not all MC-related) and too little spare time. This has gotten much worse over the past year. This is partially due to IE needing a 1.14 port (I don't think those commits will show in the activity graphic since they aren't on the main branch), and partially due to me starting to work in addition to Uni.
2. I'm unhappy about how many features turned out. The only big feature I'm currently happy with are the control panels. The mechanical multiblocks are (apparently) too complicated, since a lot of people can't figure out how to use them, and are an unstable mess code-wise. The Marx generator has some interesting concepts, but I feel like I made it far too realistic in the wrong places. The wires probably have many bugs that are near unfixable since the IC2 net isn't designed for what I'm doing.

My current plan is to port the control panels once IE for 1.14 has a release, and then try to re-add the other features without the flaws they have now (and there's a new feature I've been meaning to add since mid-2018 that I'm hoping to finally get around to as well).

**Comment by Orygeunik** [comment]
Thank you very much for answer.
Have a good time with other projects and future success

I will be wait version for 1.14 with your mod. 
Thx!

**Comment by Hawk777** [comment]
> The mechanical multiblocks are (apparently) too complicated, since a lot of people can't figure out how to use them

I have to say, I found the mechanical multiblock system, took a little bit of time to read the documentation and do some experiments, and thought they were *awesome*. Tested out RF flywheel storage, motor-generator RF-to-EU conversion, and mechanical rectifier RF-to-EU conversion; they all worked fine, how I expected them to, as documented. I’m looking forward to using them in my real world soon.

Just thought I’d mention it.
